version: "3.7"

services:

  flaskapp:
    build: ./flaskapp
    image: flaskapp:1.0.0
    container_name: flaskapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      project-custom-network:
        aliases:
          - flaskapp-alias
    expose:
      - "8080"
  
  proxy:
    build: ./nginx
    image: proxy:1.0.0
    container_name: proxy
    depends_on:
      - flaskapp
    healthcheck:
      test: ["CMD", "service", "nginx", "status", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - project-custom-network
    ports:
      - "127.0.0.1:8001:80"
      - "0.0.0.0:8002:80"

networks:
  project-custom-network:
    name: project-custom-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
